package org.jclouds.googleclouddns;

import com.google.common.annotations.Beta;

import java.io.Closeable;

/**
 * TODO: Insert description here. (generated by jkohen)
 */
@Beta
public interface GoogleCloudDnsApi extends Closeable {

}
